services:
  - type: web
    name: sentimental-analysis-dashboard
    env: python
    buildCommand: |
      pip install -r requirements.txt
      mkdir -p data
    startCommand: cd backend && python app.py
    envVars:
      - key: FLASK_ENV
        value: production
      - key: DATABASE_URL
        value: postgresql://postgres.lyxmvoamdtuwenbkjwbx:Adiman%4005@aws-0-us-east-2.pooler.supabase.com:6543/postgres
      - key: REDDIT_CLIENT_ID
        sync: false
      - key: REDDIT_CLIENT_SECRET
        sync: false
      - key: REDDIT_USERNAME
        sync: false
      - key: REDDIT_PASSWORD
        sync: false
      - key: REDDIT_USER_AGENT
        sync: false
      - key: SECRET_KEY
        sync: false

  - type: web
    name: sentimental-analysis-dashboard-1
    env: static
    buildCommand: |
      cd frontend
      npm install
      npm run build
    staticPublishPath: frontend/dist
    envVars:
      - key: NODE_ENV
        value: production
